name: Release Pipeline

on :
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  release-pipeline:
    name: Release Pipeline
    runs-on: windows-latest
    steps:
      - name: test
        run: echo "Hello, World!"

   