name: Release Pipeline

on :
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  release-pipeline:
    name: Release Pipeline
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: test
        run: dotnet test .\src\DevOpsDaysTasks.Core.Tests 


   